version: '3'
services:
  this-app:
    image: rcjmedia/react-kanban:${IMAGE_VERSION}
    depends_on:
      - db
      - redis-session-store
    command: ["./node_modules/.bin/nodemon", "server.js"]
    container_name: this-app
    volumes:
      - ".:/app/:rw"
    env_file: .prod.env
    environment:
      NODE_ENV: production
    ports:
      - "${EXPRESS_HOST_PORT}:${EXPRESS_CONTAINER_PORT}"
    networks:
      - this-app-network
  db: 
    image: postgres:10.0-alpine
    env_file: .prod.env
    volumes:
      - pg-data-volume:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}'
    networks:
      - this-app-network
  redis-session-store:
    image: redis:4.0-alpine
    env_file: .prod.env
    volumes:
      - redis-data-volume:/data
    ports:
      - '${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}'
    networks:
      - this-app-network
volumes:
    pg-data-volume:
    redis-data-volume:
networks:
  this-app-network: